spring:
  application:
    name: springboot-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8081'
  servlet:
    context-path: /api